### ISSUE TITLE
cant build it without go

### ISSUE THREAD

**Issue by reqshark** [gdamore/proxima5#7]
i want to play Proxima5, but i dont have go installed

do i have to install go to build it? and if so what version of Go should I install?

**Comment by gdamore** [comment]
Yes, you need go to build it.  Sorry, I thought that was clear.  Any
version 1.3+ should be fine.  I used 1.5.1.

**Comment by gdamore** [comment]
Closing this as a non-issue.

**Comment by reqshark** [comment]
ok let's not make too many assumptions here.. you got newbs like me out there

now I'm using go 1.5.1 and the output from `./rebuild.sh`:

``` bash
mkassets.go:30:2: cannot find package "gopkg.in/yaml.v2" in any of:
    /usr/local/go/src/gopkg.in/yaml.v2 (from $GOROOT)
    /Users/bent/work/src/gopkg.in/yaml.v2 (from $GOPATH)
```

then after installing yaml, i got:

``` bash
colors.go:18:2: cannot find package "github.com/gdamore/tcell" in any of:
    /usr/local/go/src/github.com/gdamore/tcell (from $GOROOT)
    /Users/bent/work/src/github.com/gdamore/tcell (from $GOPATH)
```

only after I had go gotten those deps did `./rebuild` compile the executable. And it's a pretty sweet game, that's what i wanted, thanks

**Comment by gdamore** [comment]
Yeah…. I probably need to make the script preinstall the dependencies. :-)

**Comment by gdamore** [comment]
Out of curiosity, what platform did you run it on?

**Comment by reqshark** [comment]
over here using OS X 10.11
